### ISSUE TITLE
Make configuration file fails trying to move in the compilation directory for dependencies

### ISSUE THREAD

**Issue by luarpy** [RafaelPalomar/Slicer-Flatpak#3]
I am trying to compile the project with ```DEBUG=true make all``` but I get the following error:
```
/bin/sh: 6: cannot create Release/cmake.out: Directory nonexistent
make: *** [Makefile:73: analyze-slicer-dependencies] Error 2
Cloning into 'Slicer'...
2 00:44 Slicer-Flatpak  Ӌ feature/slicer-flatpak-generator
 ↳ remote: Enumerating objects: 5213, done.
remote: Counting objects: 100% (5213/5213), done.
remote: Compressing objects: 100% (4193/4193), done.
remote: Total 5213 (delta 1583), reused 2283 (delta 777), pack-reused 0
Receiving objects: 100% (5213/5213), 10.87 MiB | 11.79 MiB/s, done.
Resolving deltas: 100% (1583/1583), done.
CMake Error: The source directory "/tmp/slicer-flatpak-n3vWlfPz/Slicer/2" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```
CMake & make versions:

```
0 00:45 Slicer-Flatpak  Ӌ feature/slicer-flatpak-generator
 ↳ cmake --version
cmake version 3.22.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
0 00:45 Slicer-Flatpak  Ӌ feature/slicer-flatpak-generator
 ↳ make --version
GNU Make 4.3

```

**Comment by RafaelPalomar** [comment]
@luarpy, I can't reproduce that error. Which shell are you using? 

I have added some tweaks to `feature/slicer-flatpak-generator`. Would you mind to try again and give the full output?

**Comment by luarpy** [comment]
I'm using bash
Should I change to sh?
The tweaks you added don't overcome this error

**Comment by RafaelPalomar** [comment]
> I'm using bash
> Should I change to sh?
> The tweaks you added don't overcome this error

In very rare cases, Zsh, Fish and the like can create some trouble. Bash should be fine. 

Could I get the complete output? Maybe that helps me troubleshoot the problem.

**Comment by luarpy** [comment]
[debug.txt](https://github.com/RafaelPalomar/Slicer-Flatpak/files/10993912/debug.txt)
Here it is my output debug. I tried with workarounds but they end in the same error

**Comment by RafaelPalomar** [comment]
Thanks @luarpy!

I found a couple of glitches related to redirections, variable substitution and shell compatibility. I have updated the [feature/slicer-flatpak-generator](https://github.com/RafaelPalomar/Slicer-Flatpak/tree/feature/slicer-flatpak-generator) branch.  Hopefully it works this time around. Let me know

**Comment by luarpy** [comment]
now works without problems
